深度学习


In [15]:
from dataclasses import replace

#张量
import torch
from sympy.printing.pytorch import torch


#1.定义函数
def dm01():
    t1=torch.tensor(10)
    print(t1)

    data=[[4,5,6],[1,2,3]]
    t2=torch.tensor(data)
    print(t2)
    print(type(t2))
#2.定义函数
def dmo2():
    t6=torch.Tensor(3,4)
    print(t6)
    print(type(t6))
    t5=torch.IntTensor(3,4)

    print(t5)
#3.定义函数
if __name__=='__main__':
    dm01()
    dmo2()


tensor(10)
tensor([[4, 5, 6],
        [1, 2, 3]])
<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
<class 'torch.Tensor'>
tensor([[1275202352,        706,          0,          0],
        [         0,          0,          0,          0],
        [         0,          0,          0,          0]], dtype=torch.int32)


In [51]:
#创建线性和随机张量
# arange linspace manal_seed randint
import torch
def dm01():
    t1=torch.arange(0,10,2)
    print(t1,type(t1))


    #线性等差张量
    t2=torch.linspace(1,10,4)
    print(t2,type(t2))

def dm02():
    t1=torch.rand(size=(2,3))
    print(t1,type(t1))
    torch.manual_seed(3)
    print(t1,type(t1))


    #正态分布的随机张量
    t2=torch.randn(size=(2,3))
    print(t2,type(t2))




if __name__ == '__main__':
    dm01()
    dm02()

tensor([0, 2, 4, 6, 8]) <class 'torch.Tensor'>
tensor([ 1.,  4.,  7., 10.]) <class 'torch.Tensor'>
tensor([[0.0043, 0.1056, 0.2858],
        [0.0270, 0.4716, 0.0601]]) <class 'torch.Tensor'>
tensor([[0.0043, 0.1056, 0.2858],
        [0.0270, 0.4716, 0.0601]]) <class 'torch.Tensor'>
tensor([[ 0.8033,  0.1748,  0.0890],
        [-0.6137,  0.0462, -1.3683]]) <class 'torch.Tensor'>


In [54]:
#创建指定类型的张量
# type（） double() float() short() int() long()
import torch
t1=torch.tensor([1,2,3,4,5],dtype=torch.float32)
print(t1,type(t1))

t2=t1.type(torch.int16)
print(t2,type(t2))

print(t2.half())
print(t2.double(),type(t2))
print(t2.short(),type(t2.short()))
print(t2.long(),type(t2.long()))

tensor([1., 2., 3., 4., 5.]) <class 'torch.Tensor'>
tensor([1, 2, 3, 4, 5], dtype=torch.int16) <class 'torch.Tensor'>
tensor([1., 2., 3., 4., 5.], dtype=torch.float16)
tensor([1., 2., 3., 4., 5.], dtype=torch.float64) <class 'torch.Tensor'>
tensor([1, 2, 3, 4, 5], dtype=torch.int16) <class 'torch.Tensor'>
tensor([1, 2, 3, 4, 5]) <class 'torch.Tensor'>


In [59]:
#创建全0 1   zeros() full()
t1=torch.ones(2,3)
print(t1,type(t1))

t2=t2=torch.tensor([[1,2],[3,4],[5,6]])
print(t2,type(t2))
t3=torch.ones_like(t2)
print(t3,type(t3))

t4=torch.full(size=(2,3),fill_value=255)
print(t4,type(t4))



tensor([[1., 1., 1.],
        [1., 1., 1.]]) <class 'torch.Tensor'>
tensor([[1, 2],
        [3, 4],
        [5, 6]]) <class 'torch.Tensor'>
tensor([[1, 1],
        [1, 1],
        [1, 1]]) <class 'torch.Tensor'>
tensor([[5, 5, 5],
        [5, 5, 5]]) <class 'torch.Tensor'>


In [61]:
import numpy as np


#张量和Numpy之间的转化 张量.numpy.copy
#torch.tensor(数组)
def dm01():
    t1=torch.tensor([1,2,3,4,5])
    n1=t1.numpy()
    print(n1,type(n1))

    n1[0]=100
    print(n1,type(n1))
    print(t1)

def dm02():
    n1=np.array([11,22,33])
    print(n1,type(n1))
    t1=torch.from_numpy(n1)
    print(t1,type(t1))

    t2=torch.tensor(n1)

def dm03():
    t1=torch.tensor(100)
    print(t1,type(t1))

    a=t1.item()
    print(a,type(a))



if __name__=='__main__':
    dm01()
    dm02()

[1 2 3 4 5] <class 'numpy.ndarray'>
[100   2   3   4   5] <class 'numpy.ndarray'>
tensor([100,   2,   3,   4,   5])


NameError: name 'np' is not defined

In [65]:
# 张量的基本运算 add sub mul div neg()
t1=torch.tensor([1,2,3,4,5])
print(t1.neg())
print(t1+2)

tensor([-1, -2, -3, -4, -5])
tensor([3, 4, 5, 6, 7])


In [72]:
#点乘 t1*t2
#矩阵乘法 t1@t2
def dm01():
    t1=torch.tensor([[1,2,3],[4,5,6]])
    print(t1,type(t1))

    t2=torch.tensor([[23,54,65],[4,23,234]])
    print(t2,type(t2))

    t3=t1*t2
    print(t3,type(t3))

def dm02():
    t1=torch.tensor([[1,2,3],[4,5,6]])
    print(t1,type(t1))

    t2=torch.tensor([[1,2],[3,4],[5,6]])

    print(t2,type(t2))

    t3=t1@t2
    print(t3,type(t3))
if __name__=='__main__':
    dm01()
    dm02()

tensor([[1, 2, 3],
        [4, 5, 6]]) <class 'torch.Tensor'>
tensor([[ 23,  54,  65],
        [  4,  23, 234]]) <class 'torch.Tensor'>
tensor([[  23,  108,  195],
        [  16,  115, 1404]]) <class 'torch.Tensor'>
tensor([[1, 2, 3],
        [4, 5, 6]]) <class 'torch.Tensor'>
tensor([[1, 2],
        [3, 4],
        [5, 6]]) <class 'torch.Tensor'>
tensor([[22, 28],
        [49, 64]]) <class 'torch.Tensor'>
